### Практическое задание №5

##### 5.1.
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое
внимание умножению A·B.

In [3]:
import numpy as np

In [4]:
A = np.array([[2, 0], [1, 3], [4, 9]])
B = np.array([[1, 2, 3], [2, 4, 3]])
np.dot(A, B)

array([[ 2,  4,  6],
       [ 7, 14, 12],
       [22, 44, 39]])

Вычислите, по возможности не используя программирование: (5E) −1 где Е – единичная матрица размера 5х5.

In [6]:
N = np.identity(5)
N

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
N = 5 * N
N

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [9]:
M = np.linalg.inv(N)
print(M)

[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


##### 5.2. 
Вычислите определитель:

In [10]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
round(np.linalg.det(A))

60.0

##### 5.3. 
1. Вычислите матрицу, обратную данной:

In [13]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.linalg.inv(A)
B

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

2. Приведите пример матрицы 4х4, ранг которой равен 1.

In [14]:
D = np.array([[1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0],[1, 0, 0, 0]])
D

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]])

##### 5.4.
Вычислите скалярное произведение двух векторов:

In [15]:
x = np.array([1, 5])
y = np.array([2, 8])
z = np.inner(x,y)
z

42

##### 5.5.
Вычислите смешанное произведение трех векторов:

In [16]:
x = np.array([1, 5, 0])
y = np.array([2, 8, 7])
z = np.array([7, 1.5, 3])
n = np.cross(x, y)
np.inner(n,z)

228.5

In [18]:
x = np.array([1, 5, 0])
y = np.array([2, 8, 7])
z = np.array([7, 1.5, 3])
m = np.cross(y, z)
np.inner(m,x)

228.5